parsons-skill-scout-main/parsons-skill-scout-main/jobbot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobbot/', include('parsonsjobbot.urls')),
    path('', include('landing_page.urls')),

]

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LogoutView

app_name = 'landing_page'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('jobbot/', views.redirect_to_jobbot_talent, name='redirect-to-jobbot-talent'),
    path('jobbot/resume/', views.redirect_to_jobbot_resume, name='redirect-to-jobbot-resume'),
    path('jobbot/about/', views.redirect_to_jobbot_about, name='redirect-to-jobbot-about'),
    path('jobbot/profile/', views.redirect_to_jobbot_about, name='redirect-to-jobbot-profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout')
]

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/urls.py
from django.urls import path

from . import views

#APP NAME IS THIS NOT JUST jobbot !!!!!!!!!
app_name = 'parsonsjobbot'

urlpatterns = [
    #
    # Url Patterns are expressed on this app as "http://127.0.0.1:8000/jobbot/... where the ... is the url for the paths as seen below"
    #
    # general website stuff
    path('', views.HomeView.as_view(), name='home'),
    path('landing_page/', views.redirect_to_landing_page, name='redirect-to-landing-page'),
    path('resume/', views.ResumeView.as_view(), name='resume-home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('metrics/', views.MetricsView.as_view(), name='metrics'),

    # profile suff
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit-profile'),

    # candidate stuff
    path('candidates/', views.CandidateView.as_view(), name='candidates'),
    path('candidates/<int:pk>/', views.CandidateDetailView.as_view(), name='candidate-detail'),
    path('candidates/my_candidate', views.MyCandidateProfileView.as_view(), name='my-candidate-profile'),
    path('candidates/<int:pk>/matched', views.CandidateDetailMatchedView.as_view(), name='candidate-detail-matched'),
    
    #job stuff
    path('job_submission/', views.JobSubmissionView.as_view(), name='job-submission'),
    path('job_xlsx_submission/', views.XlsxSubmissionView.as_view(), name='job-xlsx-submission'),
    path('jobs/<int:pk>/', views.JobDetailView.as_view(), name='job-detail'),

    #sow stuff
    path('sow_submission/', views.SOWSubmissionView.as_view(), name='sow-submission'),

    #Xlsx and SOW matching stuff
    path('xlsx-sow-open-matcher/', views.XlsxSOWOpenMatcherView.as_view(), name='xlsx-sow-open'),
    path('xlsx-sow-open-matcher/<int:pk>/', views.XlsxSOWOpenDeatilView.as_view(), name='xlsx-sow-open-detail'),
    path('xlsx-sow-open-matcher/<int:pk>/detail', views.XlsxSOWOpenDeatilMatchView.as_view(), name='xlsx-sow-open-detail-match'),
    

    #out of service links for now
    #path('job-rec/<int:pk>/', views.JobDetailView.as_view(), name='job-rec-detail'),
    #path('candidates/<int:pk>/job_list', views.MatchedJobsView.as_view(), name='job-list'),
]

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/models.py
from django.db import models

from django.contrib.auth.models import Group, User

# Create your models here.

#test model idk if we need it
# class Employee(models.Model):
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     years_of_experience = models.IntegerField()
#     job_title = models.CharField(max_length=100)
#     skills = models.TextField()


#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"


# from django.db import models

#dont forget to migrate!!!

class Candidate(models.Model):
    """
    This model creates a candidate class that maintains a one to one relationship with the user and holds onto information such as: 
    User, name, skills, yoe, education, and resume
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    skills = models.TextField()
    years_of_experience = models.IntegerField()
    education = models.CharField(max_length=255)
    resume = models.ForeignKey('UploadedFile', on_delete=models.CASCADE, null=True)
    # add more fields as per your requirements


    def __str__(self):
        return self.name

class UploadedFile(models.Model):
    """
    This class (not sure If we technically need it for now but I think its good to keep on file in case) maintains all files uploaded to the database
    """
    file = models.FileField(upload_to='resumes/')

    def __str__(self):
        return self.file.name

class Skill(models.Model):
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name

class JobSubmission(models.Model):
    position_id = models.CharField(max_length=50)
    position_description = models.IntegerField()
    skill_level = models.IntegerField()
    job_title = models.CharField(max_length=100)
    skills = models.ManyToManyField(Skill)


    def __str__(self):
        return f"{self.job_title} ({self.position_id})"

class UploadedXlsx(models.Model):
    """
    This class maintains all xlsx files uploaded to the database
    """
    file = models.FileField(upload_to='SOWs/')

    def __str__(self):
        return self.file.name

class XlsxJob(models.Model):
    tonum = models.CharField(max_length=100) 
    posnum = models.CharField(max_length=100)
    pdnum = models.CharField(max_length=100) 
    previous_names = models.CharField(max_length=100) 
    project = models.CharField(max_length=100) 
    status = models.CharField(max_length=100)
    labor_cat = models.CharField(max_length=100)
    level = models.CharField(max_length=100)
    clin = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    release_date = models.CharField(max_length=100)
    open_or_closed = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"This is Position can be found on TONum: {self.tonum} (Position: {self.posnum}) and this position is {self.open_or_closed}."

class UploadedSOW(models.Model):
    """
    This class maintains all SOW files uploaded to the database
    """

    file = models.FileField(upload_to='SOWs/')

    def __str__(self):
        return self.file.name

class SOWPosition(models.Model):
    tonum = models.CharField(max_length=100)
    pos_id = models.CharField(max_length=100)
    posnum = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    posdescnum = models.CharField(max_length=100)
    posdesctitle = models.CharField(max_length=100)
    posdesc = models.TextField(default='Position Description Goes Here')
    level = models.CharField(max_length=100)
    service_cat = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    #xlsx_job = models.ForeignKey(XlsxJob, on_delete=models.CASCADE, related_name='sow_positions', null=True)

    def __str__(self):
        return f"This is SOW Position {self.pos_id} found on Task Order {self.tonum}"
    
    @property
    def posdesc_preview(self):
        preview_length = 100  # Adjust the desired length
        if len(self.posdesc) > preview_length:
            return self.posdesc[:preview_length] + "..."
        return self.posdesc

    class Meta:
        verbose_name_plural = 'SOW Positions'

class SimilarityScoreMatcher(models.Model):
    candidate_name = models.CharField(max_length=255)
    candidate_info = models.TextField()
    #sow_pos = models.CharField(max_length=255)
    sow_info = models.TextField()
    similarity_score = models.FloatField()

    def __str__(self):
        return f"Candidate {self.candidate_name} has a similarity score of {self.similarity_score} for the position"
    
    @property
    def candidate_info_preview(self):
        preview_length = 100  # Adjust the desired length
        if len(self.candidate_info) > preview_length:
            return self.candidate_info[:preview_length] + "..."
        return self.candidate_info

    @property
    def sow_info_preview(self):
        preview_length = 100  # Adjust the desired length
        if len(self.sow_info) > preview_length:
            return self.sow_info[:preview_length] + "..."
        return self.sow_info

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/forms.py
from django import forms
from django.core.exceptions import ValidationError
import os
from django.contrib.auth.models import User

class ResumeUploadForm(forms.Form):
    """
    If you want to make more fields to put in for the HTML for resume uploading put them here first and then use the variable name
    in the views similarly to the others to make another field.
    """
    resume = forms.FileField(label='Upload Resume', widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}))
    years_of_experience = forms.IntegerField(label='Years of Experience')
    education = forms.CharField(label='Education', max_length=255)
    name = forms.CharField(label='Name', max_length=255)
    is_own_resume = forms.BooleanField(label='Is this your own resume?', required=False)

    def clean_resume(self):
        resume = self.cleaned_data['resume']
        filename = resume.name
        allowed_extensions = ['.pdf', '.doc', '.docx']
        ext = os.path.splitext(filename)[1].lower()


        if ext not in allowed_extensions:
            raise ValidationError("Unsupported file extension. Please upload a PDF, DOC, or DOCX file.")


        return resume
    
class XlsxUploadForm(forms.Form):
    """
    If you want to make more fields to put in for the HTML for resume uploading put them here first and then use the variable name
    in the views similarly to the others to make another field.
    """
    xlsx = forms.FileField(label='Upload Xlsx', widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}))

    def clean_xlsx(self):
        xlsx = self.cleaned_data['xlsx']
        filename = xlsx.name
        allowed_extensions = ['.xlsx']
        ext = os.path.splitext(filename)[1].lower()


        if ext not in allowed_extensions:
            raise ValidationError("Unsupported file extension. Please upload a XLSX file.")


        return xlsx

class SOWUploadForm(forms.Form):
    """
    If you want to make more fields to put in for the HTML for resume uploading put them here first and then use the variable name
    in the views similarly to the others to make another field.
    """
    sow = forms.FileField(label='Upload SOW', widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}))

    def clean_sow(self):
        sow = self.cleaned_data['sow']
        filename = sow.name
        allowed_extensions = ['.pdf', '.docx', '.doc']
        ext = os.path.splitext(filename)[1].lower()


        if ext not in allowed_extensions:
            raise ValidationError("Unsupported file extension. Please upload a PDF or DOCX file.")


        return sow

class UserSelectionForm(forms.Form):
    """
    
    This form is intended to swap a user out with a floating candidate

    NOT IMPLEMENTED AS OF NOW (1/5/2024)
    
    """
    user = forms.ModelChoiceField(queryset=User.objects.all(), empty_label="Select a user")

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/templates/parsonsjobbot/base.html
{% load static %}
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Parsons">
    <meta name="description" content="Parsons Skill Scout {% block description %}{% endblock %} page">
    <meta name="keywords" content="hiring, Parsons, jobs">
    <link rel="icon" href="/static/parsonsjobbot/icon.png">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">


    <title>Parsons Skill Scout - {% block title %}{% endblock %}</title>


    <style>
        body {
            background-image: url("{% static 'parsonsjobbot/background.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'parsonsjobbot/talentsurfer.css' %}">
</head>


<body class="d-flex flex-column h-100">
<header class="container-fluid ps-4" style="background-color:#0a1d30; border-bottom: 10px solid #20344c;">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <img src="{% static 'parsonsjobbot/parsons_logo.png' %}" alt="Logo" class="navbar-logo" width="300">
        <a class="navbar-brand fw-bold fs-1 text-white" href="{% url 'landing_page:landing_page' %}">
            Skill Scout - {% block navtitle %}{% endblock %}
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item" title="Profile Image">
                      <a style="background-color: white; border-radius: 100%; margin-right: 10px;" class="nav-link" href="{% url 'landing_page:redirect-to-jobbot-profile' %}" target="_blank" rel="noopener noreferrer">
                        <img src="{% static 'landing_page/user_logo.png' %}" alt="User Logo" style="width:25px;height:25px;">
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="{% url 'parsonsjobbot:profile' %}">View Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'landing_page:logout' %}" onclick="confirmLogout()">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'landing_page:login' %}">Login</a>
                    </li>
                {% endif %}
                
                <li class="nav-item">
                    <a class="nav-link text-white" href="https://www.parsons.com/life/">About Parsons</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<div class= "container-scroll">
{% block content %}{% endblock %}
</div>


<footer class="footer mt-auto text-center bg-light">
    <div class="p-3 text-muted" style="background-color:#0a1d30;">
        &copy; 2023 Parsons. All rights reserved.
        <a class="text-reset" href="https://www.parsons.com/">Parsons</a>
    </div>
</footer>


<script>
    function confirmLogout() {
        return confirm("Are you sure you want to logout?");
    }
</script>
</body>
</html>

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/templates/parsonsjobbot/edit_profile.html
{% extends "parsonsjobbot/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block description %}Profile Edit{% endblock %}
{% block title %}Profile Edit{% endblock %}
{% block navtitle %}Profile Edit{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5" style="color: white;">
            <h1>Edit Profile</h1>
            <form method="post" action="{% url 'parsonsjobbot:edit-profile' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="name" class="form-control" value="{{ user.get_full_name }}">
                </div>
                <div class="form-group">
                    <label for="groups">Groups:</label>
                    <select id="groups" name="groups" class="form-control" multiple>
                        {% for group in groups %}
                            <option value="{{ group.id }}" {% if group in user.groups.all %}selected{% endif %}>{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            <ul class="list-unstyled">
                <li style="margin-bottom: 50px; margin-top: 30px;">
                    <a href="{% url 'landing_page:landing_page' %}" class="btn-talent-surfer-page">Go to Home Page</a>
                    <a href="{% url 'parsonsjobbot:home' %}" class="btn-talent-surfer-page">Go to Talent Surfer</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% else %}
<body>
    <div class="container-scroll">
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 75vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="d-flex flex-column">
                        <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                        <p class="login-statement" style="color: white; font-size: 32px;">We are excited to have you join Skill Scout, but first we need you to login.</p>
                        <a class="btn-talent-surfer-page" href="{% url 'landing_page:login' %}">Login</a>
                        <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer-page">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}

  
{% endblock %}

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/templates/parsonsjobbot/job_listing.html
{% extends "parsonsjobbot/base.html"%}
{% load static %}
{% block description %}Job Listings{% endblock %}
{% block title %}Job Listings{% endblock %}
{% block navtitle %}Job Listings{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}

<!-- THIS HTML IS NO LONGER RELEVANT FOR NOW (07/20/2023) -->

{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 style="color: white; 64px;">Job Listings - {{ candidate.name }}</h1>
            
            {% if matched_jobs %}
                <div class="resume-list" style="border: 1px solid white; padding: 25px; margin-bottom: 25px; display: inline-block; max-width: 500px; width: 100%">
                    <h1 style="color: white; margin-bottom: 25px;">Matched Jobs</h1>
                
                    <div class="resume-item">
                        <ul class="list-unstyled">
                            {% for sow_position, similarity_score in matched_jobs %}
                            <li style="color: white;">
                                <a href="{% url 'parsonsjobbot:xlsx-sow-open-detail' sow_position.pk %}" class="btn-talent-surfer-page" style="color: white;">
                                    {{ sow_position.job_title }}: {{ similarity_score|floatformat:2 }}%
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% else %}
                <p style="color: white;">No jobs seemed to have matched for now.</p>
            {% endif %}

            
            <ul class="list-unstyled">
                <li style="margin-bottom: 10px;">
                    <a href="{% url 'landing_page:landing_page' %}" class="btn-talent-surfer-page">Go to Home Page</a>
                    <a href="{% url 'parsonsjobbot:candidate-detail' pk=candidate.pk %}" class="btn-talent-surfer-page">Back to Candidate Profile</a>
                </li>
            </ul>
        </div>
    </div>
</div>

{% else %}
<body>
    <div class="container-scroll">
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 75vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="d-flex flex-column">
                        <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                        <p class="login-statement" style="color: white; font-size: 32px;">We are excited to have you join Skill Scout, but first we need you to login.</p>
                        <a class="btn-talent-surfer-page" href="{% url 'landing_page:login' %}">Login</a>
                        <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer-page">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}
{% endblock %}

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/templates/parsonsjobbot/job_submission.html
{% extends "parsonsjobbot/base.html"%}
{% load static %}
{% load auth_extras %}
{% block description %}Job Submission{% endblock %}
{% block title %}Job Submission{% endblock %}
{% block navtitle %}Job Submission{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}



{% block content %}
{% if user.is_authenticated%}
{% if request.user|has_group:"TOPM" or request.user|has_group:"TA" or request.user|has_group:"PM" or request.user|has_group:"Admin" %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <h1 style="color: white; 64px;">Job Submission</h1>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: white; font-size: 32px;">{{ message.message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p style="color: white;">Content of this page will be here for now</p>
                <form method="post" style="color: white;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <label for="id_skills">Skills:</label> <input type="text" id="id_skills" name="skills" placeholder="Enter skills separated by commas">
                    <ul class="list-unstyled">
                        <li style="margin-bottom: 10px; margin-top: 20px;">
                            <button type="submit" class="btn-talent-surfer-page">Submit</button>
                        </li>
                    </ul>   
                </form>
                <ul class="list-unstyled">
                    <li style="margin-bottom: 10px;">
                        <a href="{% url 'landing_page:landing_page' %}" class="btn-talent-surfer-page">Go to Home Page</a> 
                        <a href="{% url 'parsonsjobbot:home' %}" class="btn-talent-surfer-page">Return to Talent Surfer</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% else %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <p style="color: white;">Oops! You aren't supposed to be here are you?</p>
                <ul class="list-unstyled">
                    <li style="margin-bottom: 10px;">
                        <a href="{% url 'landing_page:landing_page' %}" class="btn-talent-surfer-page">Go to Home Page</a> 
                        <a href="{% url 'parsonsjobbot:home' %}" class="btn-talent-surfer-page">Return to Talent Surfer</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
{% else %}
<body>
    <div class="container-scroll">
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 75vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="d-flex flex-column">
                        <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                        <p class="login-statement" style="color: white; font-size: 32px;">We are excited to have you join Skill Scout, but first we need you to login.</p>
                        <a class="btn-talent-surfer-page" href="{% url 'landing_page:login' %}">Login</a>
                        <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer-page">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}
{% endblock %}

parsons-skill-scout-main/parsons-skill-scout-main/parsonsjobbot/templates/parsonsjobbot/profile.html
{% extends "parsonsjobbot/base.html"%}
{% load static %}
{% block description %}Profile{% endblock %}
{% block title %}Profile{% endblock %}
{% block navtitle %}Profile{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}



{% block content %}
{% if user.is_authenticated %}
<div class="parent-container d-flex align-items-center justify-content-center vh-100">
    <div class="container text-center">
        <h1 style="color: white; font-size: 64px;">Profile</h1>
        <div class="d-inline-block p-4" style="background-color: white; border-radius: 10px;">
            <p style="color: black;">Welcome to your profile page. Here, you can view and manage your profile information and settings.</p>
            <p style="color: black;"><strong>User:</strong> {{ user }}</p>
            <p style="color: black;"><strong>Name:</strong> {{ name }}</p>
            <p style="color: black;"><strong>Groups:</strong></p>
            <ul style="color: black; list-style: none; padding: 0;">
                {% for group in groups %}
                <li>{{ group.name }}</li>
                {% endfor %}
            </ul>
            <a href="{% url 'parsonsjobbot:edit-profile' %}" class="btn btn-primary">Edit</a>
        </div>
        <ul class="list-unstyled">
            <li style="margin-bottom: 50px; margin-top: 30px;">
                <a href="{% url 'landing_page:landing_page' %}" class="btn-talent-surfer-page">Go to Home Page</a>
                <a href="{% url 'parsonsjobbot:home' %}" class="btn-talent-surfer-page">Go to Talent Surfer</a>
            </li>
        </ul>
    </div>
</div>



{% else %}
<body>
    <div class="container-scroll">
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 75vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="d-flex flex-column">
                        <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                        <p class="login-statement" style="color: white; font-size: 32px;">We are excited to have you join Skill Scout, but first we need you to login.</p>
                        <a class="btn-talent-surfer-page" href="{% url 'landing_page:login' %}">Login</a>
                        <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer-page">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}
{% endblock %}