parsons-skill-scout-main/parsons-skill-scout-main/jobbot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobbot/', include('parsonsjobbot.urls')),
    path('', include('landing_page.urls')),

]

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LogoutView

app_name = 'landing_page'

urlpatterns = [
    path('', views.LandingView.as_view(), name='landing_page'),
    path('jobbot/', views.redirect_to_jobbot_talent, name='redirect-to-jobbot-talent'),
    path('jobbot/resume/', views.redirect_to_jobbot_resume, name='redirect-to-jobbot-resume'),
    path('jobbot/about/', views.redirect_to_jobbot_about, name='redirect-to-jobbot-about'),
    path('jobbot/profile/', views.redirect_to_jobbot_about, name='redirect-to-jobbot-profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout')
]

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/models.py
from django.db import models

# Create your models here.

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.views import generic
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User
from django import forms
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib import messages


# Create your views here.

# def landing_page(request):
#     template_name = 'landing_page/landing_page.html'
#     return render(request, template_name)

class LandingView(generic.TemplateView):
    """
    Rendered HTML file, no backend impact
    """
    template_name = 'landing_page/landing_page.html'
    context_object_name = 'landing_page'

class LoginView(LoginView):
    """
    This is necessary for all users who want to use skill scout, 
    login queries the database for a valid login credential, 
    LoginView import naturally will do this, no need to do anything.
    """
    template_name = 'landing_page/login.html'
    success_url = reverse_lazy('landing_page:landing_page')

class ExtendedSignupForm(UserCreationForm):
    """
    Creates additional fields for the signup of a new user.
    """
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)


    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')


class SignupView(FormView):
    """
    This View will query the user to make a username and input things such as their email and name and will then set it in the backend as a user
    """
    template_name = 'landing_page/signup.html'
    form_class = ExtendedSignupForm
    success_url = reverse_lazy('landing_page:login')


    def form_valid(self, form):
        user = form.save()
        group = form.cleaned_data['group']
        user.groups.add(group)
        messages.success(self.request, 'Your account has been created successfully.')
        return super().form_valid(form)



def redirect_to_jobbot_talent(request):
    """
    goes to the other app parsonsjobbot, jobbot:name will query the whole project for a name corresponding
    """
    return redirect('jobbot:home')

def redirect_to_jobbot_resume(request):
    """
    goes to the other app parsonsjobbot, jobbot:name will query the whole project for a name corresponding
    """
    return redirect('jobbot:resume-home')

def redirect_to_jobbot_about(request):
    """
    goes to the other app parsonsjobbot, jobbot:name will query the whole project for a name corresponding
    """
    return redirect('jobbot:about')

def redirect_to_jobbot_profile(request):
    """
    goes to the other app parsonsjobbot, jobbot:name will query the whole project for a name corresponding
    """
    return redirect('jobbot:profile')

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/templates/landing_page/base.html
{% load static %}
<html lang="en" class="h-100">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Parsons">
        <meta name="description" content="Parsons Skill Scout {% block description %}{% endblock %} page">
        <meta name="keywords" content="hiring, Parsons, jobs">
        <link rel="icon" href="/static/landing_page/landing_favicon.png">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> 
      
        <title>Parsons Skill Scout - {% block title %}{% endblock %}</title>

        <style>
          body {
            background-image: url("{% static 'landing_page/background.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
          }
        </style>

      
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'landing_page/style.css' %}">
    </head>

    <body class="d-flex flex-column h-100">
      <header class="container-fluid ps-4" style="background-color:#0a1d30; border-bottom: 10px solid #20344c;">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <img src="{% static 'landing_page/parsons_logo.png' %}" alt="Logo" class="navbar-logo" width="300">
          <a class="navbar-brand fw-bold fs-1 text-white" href="{% url 'landing_page:landing_page' %}">
            Skill Scout - {% block navtitle %}{% endblock %}
          </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
                <li class="nav-item" title="Profile Image">
                  <a style="background-color: white; border-radius: 100%; margin-right: 10px;" class="nav-link" href="{% url 'landing_page:redirect-to-jobbot-profile' %}" target="_blank" rel="noopener noreferrer">
                    <img src="{% static 'landing_page/user_logo.png' %}" alt="User Logo" style="width:25px;height:25px;">
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'landing_page:redirect-to-jobbot-profile' %}">View Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#" onclick="confirmLogout()">Logout</a>

                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'landing_page:login' %}">Login</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link text-white" href="https://www.parsons.com/life/">About Parsons</a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
    
    
      
      {% block content %}{% endblock %}


      <script src="{% static 'landing_page/rotating-messages.js' %}"></script>
      <script>
        function confirmLogout() {
            if (confirm('Are you sure you want to log out?')) {
                window.location.href = "{% url 'landing_page:logout' %}";
            }
        }
      </script>
    

      <footer class="footer mt-auto text-center bg-light">
        <div class="p-3 text-muted" style="background-color:#0a1d30;">
          © 2023 Copyright:
          <a class="text-reset" href="https://www.parsons.com/">Parsons</a>
        </div>
      </footer>
    </body>

    
</html>

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/templates/landing_page/landing_page.html
{% extends "landing_page/base.html" %}
{% load static %}
{% block description %}Landing Page{% endblock %}
{% block title %}Landing Page{% endblock %}
{% block navtitle %}Home{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}


{% block content %}
{% if user.is_authenticated %}
<div class="container-scroll">
<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5" style="margin-bottom: 100px;">
            <div class="homepage" style="color: white; border: 1px solid white; padding: 25px; margin-bottom: 25px; background-color: rgba(0, 0, 0, 0.3); box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); ">
                <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                <p id="rotating-text" class="rotating-text"></p>
                <a href="{% url 'landing_page:redirect-to-jobbot-resume' %}" class="btn-talent-surfer">Submit a Resumé</a>
                <a href="{% url 'landing_page:redirect-to-jobbot-talent' %}" class="btn-talent-surfer">Go to Talent Surfer</a>
            </div>
        </div>
    </div>
</div>

    <div class="container mt-auto mb-3">
        <div class="row">
            <div class="col-12 text-center">
                <div class="homepage" style="color: white; border: 1px solid white; padding: 25px; margin-bottom: 25px; background-color: rgba(0, 0, 0, 0.3); box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); ">
                    <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>                        
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer">Learn More</a>
                    </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<body>
    <div class="container-scroll">
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 75vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="d-flex flex-column">
                        <h1 style="color: white; font-size: 64px;">Skill Scout Home</h1>
                        <p class="login-statement" style="color: white; font-size: 32px;">We are excited to have you join Skill Scout, but first we need you to login.</p>
                        <a class="btn-talent-surfer" href="{% url 'landing_page:login' %}">Login</a>
                        <h1 style="color: white; font-size: 64px;">What is Skill Scout?</h1>
                        <p style="color: white; font-size: 24px;">
                            Skill Scout is an innovative application currently being developed here at Parsons.
                            Skill Scout aims to connect job seekers within and outside of Parsons to a vast network of opportunities, helping individuals find their dream careers.
                            Our platform utilizes cutting-edge technology and leverages the expertise of Parsons to match users with the perfect job based on their skills, aspirations, and unique talents.
                            Whether you are an employee, intern, or someone seeking new professional opportunities, Skill Scout is here to support you in your journey towards success.
                        </p>
                        <a href="{% url 'landing_page:redirect-to-jobbot-about' %}" class="btn-talent-surfer">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endif %}



{% endblock %}

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/templates/landing_page/login.html
{% extends "landing_page/base.html" %}
{% load static %}
{% block description %}Login Page{% endblock %}
{% block title %}Login Page{% endblock %}
{% block navtitle %}Login{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}




{% block content %}
<style>
    .login-box {
        background-color: #ffffff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    
    .login-title {
        color: #000000;
        font-size: 28px;
        margin-bottom: 20px;
    }
    
    .login-form {
        margin-bottom: 20px;
    }
    
    .form-group {
        margin-bottom: 15px;
    }
    
    .form-group label {
        font-weight: bold;
    }
    
    .form-control {
        border: 1px solid #cccccc;
        border-radius: 5px;
        padding: 10px;
        width: 100%;
    }
    
    .login-button {
        background-color: #20344c;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-weight: bold;
        cursor: pointer;
    }
    
    .login-button:hover {
        background-color: #1a2e40;
    }
    
    .login-link {
        margin-right: 10px;
        font-weight: bold;
        color: #20344c;
        text-decoration: none;
    }
    
    .login-link:hover {
        text-decoration: underline;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <div class="login-box">
                <h1 class="login-title">Login</h1>
                <form class="login-form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Username</label>
                        <input type="text" name="username" id="id_username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" name="password" id="id_password" class="form-control">
                    </div>
                    <button type="submit" class="login-button">Login</button>
                </form>
                <a href="{% url 'landing_page:landing_page' %}" class="login-link">Back to Home Page</a>
                <a href="{% url 'landing_page:signup' %}" class="login-link">Sign up</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

parsons-skill-scout-main/parsons-skill-scout-main/landing_page/templates/landing_page/signup.html
{% extends "landing_page/base.html" %}
{% load static %}
{% block description %}Signup Page{% endblock %}
{% block title %}Signup Page{% endblock %}
{% block navtitle %}Sign up{% endblock %}
{% block something-link-style %}fw-bold{% endblock %}


{% block content %}
<style>
    .signup-box {
        background-color: #ffffff;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    
    .signup-title {
        color: #000000;
        font-size: 28px;
        margin-bottom: 20px;
    }
    
    .signup-form {
        margin-bottom: 20px;
    }
    
    .form-group {
        margin-bottom: 15px;
    }
    
    .form-group label {
        font-weight: bold;
    }
    
    .form-control {
        border: 1px solid #cccccc;
        border-radius: 5px;
        padding: 10px;
        width: 100%;
    }
    
    .signup-button {
        background-color: #20344c;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-weight: bold;
        cursor: pointer;
    }
    
    .signup-button:hover {
        background-color: #1a2e40;
    }
    
    .signup-link {
        margin-right: 10px;
        font-weight: bold;
        color: #20344c;
        text-decoration: none;
    }
    
    .signup-link:hover {
        text-decoration: underline;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-12 text-center mt-5">
            <div class="signup-box">
                <h1 class="signup-title">Signup</h1>
                <form class="signup-form" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="signup-button">Sign Up</button>
                </form>
                <a href="{% url 'landing_page:landing_page' %}" class="signup-link">Back to Home Page</a>
                <a href="{% url 'landing_page:login' %}" class="signup-link">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}